---
name: Test-Perl-Dist
version: 0.202
author:
  - 'Curtis Jewell <CSJewell@cpan.org>'
abstract: Test module for Perl::Dist::WiX and subclasses
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-Perl-Dist
  homepage: http://csjewell.comyr.com/perl/
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Test-Perl-Dist/
build_requires:
  Test::More: 0.88
requires:
  File::Remove: 1.42
  LWP::Online: 1.07
  Test::More: 0.88
  URI: 1.4
  Win32: 0.39
  parent: 0.221
  perl: 5.008001
configure_requires:
  Module::Build: 0.33
provides:
  Test::Perl::Dist:
    file: lib/Test/Perl/Dist.pm
    version: 0.202
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
